from ex1 import HealingCreatureFactory, TransformCreatureFactory


if __name__ == "__main__":
    healing_factory = HealingCreatureFactory()
    sproutling = healing_factory.create_base()
    bloomelle = healing_factory.create_evolved()
    print(sproutling.describe())
    print(sproutling.attack())
    print(sproutling.heal())
    print(bloomelle.describe())
    print(bloomelle.attack())
    print(bloomelle.heal())
    transform_factory = TransformCreatureFactory()
    shiftling = transform_factory.create_base()
    print(shiftling.describe())
    print(shiftling.attack())
    print(shiftling.transform())
    print(shiftling.attack())
    print(shiftling.revert())
    morphagon = transform_factory.create_evolved()
    print(morphagon.describe())
    print(morphagon.attack())
    print(morphagon.transform())
    print(morphagon.attack())
    print(morphagon.revert())
